project:
  type: book

book:
  title: "GLAIEULS"
  subtitle: "in XDV/hompl"
  author: "GranPiero"
  date: now
  chapters:
    - index.qmd
    - parcelles.qmd
    - urbanisme.qmd
    - demolition.qmd
    - summary_prix.qmd

format:
  pdf:
    documentclass: scrreprt
    geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
  html:
    theme: cosmo


